version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/docs/site"
      - "/examples/plugins/shelly-tasmota"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      go-modules:
        patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker:
        patterns: ["*"]
