# Funding platforms for the Shelly CLI project
# Uncomment and configure as needed

github: [tj-smith47]
# patreon: username
# open_collective: shelly-cli
# ko_fi: username
# tidelift: npm/package-name
# custom: ["https://your-donation-link.com"]
