version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test -race ./...

builds:
  - id: shelly
    main: ./cmd/shelly
    binary: shelly
    # CGO_ENABLED is set per-platform in CI workflow for BLE support
    # - Linux/macOS: CGO_ENABLED=1 (BlueZ/CoreBluetooth)
    # - Windows: CGO_ENABLED=0 (WinRT BLE doesn't require CGO)
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64  # Skip Windows ARM64
    ldflags:
      - -s -w
      - -X github.com/tj-smith47/shelly-cli/internal/version.Version={{.Version}}
      - -X github.com/tj-smith47/shelly-cli/internal/version.Commit={{.Commit}}
      - -X github.com/tj-smith47/shelly-cli/internal/version.Date={{.Date}}
      - -X github.com/tj-smith47/shelly-cli/internal/version.BuiltBy=goreleaser
    flags:
      - -trimpath

# =============================================================================
# Split/Merge for multi-platform CGO builds (GoReleaser Pro feature)
# =============================================================================
# When using Pro, run with: goreleaser release --split on each platform runner
# Then merge with: goreleaser continue --merge
partial:
  by: goos

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - NOTICE
      - README.md
      - CHANGELOG.md
      - completions/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"

release:
  github:
    owner: tj-smith47
    name: shelly-cli
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    ### Homebrew (macOS)
    ```bash
    brew install tj-smith47/tap/shelly
    ```

    ### Go Install (All Platforms)
    ```bash
    go install github.com/tj-smith47/shelly-cli/cmd/shelly@v{{.Version}}
    ```

    ### Docker (Linux)
    ```bash
    docker pull ghcr.io/tj-smith47/shelly-cli:{{.Version}}
    docker run --rm ghcr.io/tj-smith47/shelly-cli:{{.Version}} --help
    ```

    ### Download Binary
    Download the appropriate binary for your platform from the assets below.

    ## BLE Support

    | Platform | BLE Discovery | BLE Provisioning |
    |----------|---------------|------------------|
    | Linux | ✅ Requires BlueZ | ✅ |
    | macOS | ✅ Built-in | ✅ |
    | Windows | ✅ Built-in | ✅ |

    ## What's Changed
    See the [CHANGELOG](https://github.com/tj-smith47/shelly-cli/blob/master/CHANGELOG.md) for details.

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

# =============================================================================
# Docker Images (ghcr.io) - using dockers_v2 for multi-arch support
# =============================================================================

dockers_v2:
  - images:
      - "ghcr.io/tj-smith47/shelly-cli"
    tags:
      - "{{ .Version }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "Shelly CLI"
      org.opencontainers.image.description: "Command-line interface for Shelly smart home devices"
      org.opencontainers.image.url: "https://github.com/tj-smith47/shelly-cli"
      org.opencontainers.image.source: "https://github.com/tj-smith47/shelly-cli"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.licenses: "Apache-2.0"

# =============================================================================
# Homebrew Tap - native macOS binaries with full BLE support
# =============================================================================
brews:
  - name: shelly
    repository:
      owner: tj-smith47
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/tj-smith47/shelly-cli"
    description: "Command-line interface for Shelly smart home devices with full BLE support"
    license: "Apache-2.0"
    install: |
      bin.install "shelly"
      generate_completions_from_executable(bin/"shelly", "completion")
    test: |
      system "#{bin}/shelly", "--version"
