name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: category
    attributes:
      label: Feature category
      options:
        - New command
        - Enhancement to existing command
        - TUI dashboard
        - Configuration
        - Output formatting
        - Shell completions
        - Plugin system
        - Theme support
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this feature solve? What's your use case?
      placeholder: "I frequently need to... but currently..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
      placeholder: |
        I'd like a command like:
        ```
        shelly myfeature --flag value
        ```
        This would...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Example usage
      description: Show example commands or output
      render: shell
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Would use regularly
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
          required: false
        - label: I'm willing to test a PR for this feature
          required: false
