// Package terraform provides the export terraform subcommand.
package terraform

import (
	"context"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/spf13/cobra"

	"github.com/tj-smith47/shelly-cli/internal/cmdutil"
	"github.com/tj-smith47/shelly-cli/internal/completion"
	"github.com/tj-smith47/shelly-cli/internal/iostreams"
	"github.com/tj-smith47/shelly-cli/internal/shelly"
)

// tfExtensions defines valid Terraform file extensions.
var tfExtensions = []string{".tf"}

// Options holds command options.
type Options struct {
	Devices      []string
	File         string
	ResourceName string
	Factory      *cmdutil.Factory
}

// NewCommand creates the export terraform command.
func NewCommand(f *cmdutil.Factory) *cobra.Command {
	opts := &Options{Factory: f}

	cmd := &cobra.Command{
		Use:     "terraform <devices...> [file]",
		Aliases: []string{"tf"},
		Short:   "Export devices as Terraform configuration",
		Long: `Export devices as Terraform local values configuration.

Creates a Terraform locals block with device information that can be
used as data source for infrastructure as code workflows.`,
		Example: `  # Export to stdout
  shelly export terraform @all

  # Export to file
  shelly export terraform @all shelly.tf

  # Export with custom resource name
  shelly export terraform @all --resource-name my_shelly_devices`,
		Args:              cobra.MinimumNArgs(1),
		ValidArgsFunction: completion.DevicesWithGroups(),
		RunE: func(cmd *cobra.Command, args []string) error {
			opts.Devices, opts.File = cmdutil.SplitDevicesAndFile(args, tfExtensions)
			return run(cmd.Context(), opts)
		},
	}

	cmd.Flags().StringVar(&opts.ResourceName, "resource-name", "shelly_devices", "Terraform local variable name")

	return cmd
}

// Device represents a device in Terraform format.
type Device struct {
	Name       string
	Address    string
	Model      string
	Generation int
	App        string
}

const terraformTemplate = `# Shelly devices configuration
# Generated by shelly-cli

locals {
  {{.ResourceName}} = {
{{- range .Devices}}
    "{{.Name}}" = {
      address    = "{{.Address}}"
      model      = "{{.Model}}"
      generation = {{.Generation}}
{{- if .App}}
      app        = "{{.App}}"
{{- end}}
    }
{{- end}}
  }
}

# Example usage:
# resource "null_resource" "shelly_config" {
#   for_each = local.{{.ResourceName}}
#   triggers = {
#     address = each.value.address
#   }
# }
`

func run(ctx context.Context, opts *Options) error {
	ctx, cancel := context.WithTimeout(ctx, 2*shelly.DefaultTimeout)
	defer cancel()

	ios := opts.Factory.IOStreams()
	svc := opts.Factory.ShellyService()

	// Expand @all to all registered devices
	devices := completion.ExpandDeviceArgs(opts.Devices)
	if len(devices) == 0 {
		return fmt.Errorf("no devices specified")
	}

	// Collect device data using shared helper
	var deviceData []cmdutil.DeviceData
	err := cmdutil.RunWithSpinner(ctx, ios, "Fetching device data...", func(ctx context.Context) error {
		deviceData = cmdutil.CollectDeviceData(ctx, svc, devices)
		return nil
	})
	if err != nil {
		return err
	}

	// Convert to terraform Device format with normalized names
	tfDevices := make([]Device, 0, len(deviceData))
	for _, d := range deviceData {
		tfDevices = append(tfDevices, Device{
			Name:       normalizeResourceName(d.Name),
			Address:    d.Address,
			Model:      d.Model,
			Generation: d.Generation,
			App:        d.App,
		})
	}

	// Generate Terraform config
	tmpl, err := template.New("terraform").Parse(terraformTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	data := struct {
		ResourceName string
		Devices      []Device
	}{
		ResourceName: opts.ResourceName,
		Devices:      tfDevices,
	}

	// Output
	if opts.File == "" {
		return tmpl.Execute(ios.Out, data)
	}

	file, err := os.Create(opts.File)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer iostreams.CloseWithDebug("closing terraform export file", file)

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	ios.Success("Exported %d devices to %s", len(tfDevices), opts.File)
	return nil
}

// normalizeResourceName converts a device name to a valid Terraform identifier.
func normalizeResourceName(name string) string {
	result := strings.ToLower(name)
	result = strings.ReplaceAll(result, " ", "_")
	result = strings.ReplaceAll(result, "-", "_")
	result = strings.ReplaceAll(result, ".", "_")
	return result
}
