// Package terraform provides the export terraform subcommand.
package terraform

import (
	"context"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/spf13/cobra"

	"github.com/tj-smith47/shelly-cli/internal/client"
	"github.com/tj-smith47/shelly-cli/internal/cmdutil"
	"github.com/tj-smith47/shelly-cli/internal/config"
	"github.com/tj-smith47/shelly-cli/internal/iostreams"
	"github.com/tj-smith47/shelly-cli/internal/shelly"
)

// Options holds command options.
type Options struct {
	Devices      []string
	File         string
	ResourceName string
	Factory      *cmdutil.Factory
}

// NewCommand creates the export terraform command.
func NewCommand(f *cmdutil.Factory) *cobra.Command {
	opts := &Options{Factory: f}

	cmd := &cobra.Command{
		Use:   "terraform <devices...> [file]",
		Short: "Export devices as Terraform configuration",
		Long: `Export devices as Terraform local values configuration.

Creates a Terraform locals block with device information that can be
used as data source for infrastructure as code workflows.`,
		Example: `  # Export to stdout
  shelly export terraform @all

  # Export to file
  shelly export terraform @all shelly.tf

  # Export with custom resource name
  shelly export terraform @all --resource-name my_shelly_devices`,
		Args:              cobra.MinimumNArgs(1),
		ValidArgsFunction: cmdutil.CompleteDevicesWithGroups(),
		RunE: func(cmd *cobra.Command, args []string) error {
			// Check if last arg is a file
			if len(args) > 1 && strings.HasSuffix(args[len(args)-1], ".tf") {
				opts.File = args[len(args)-1]
				opts.Devices = args[:len(args)-1]
			} else {
				opts.Devices = args
			}
			return run(cmd.Context(), opts)
		},
	}

	cmd.Flags().StringVar(&opts.ResourceName, "resource-name", "shelly_devices", "Terraform local variable name")

	return cmd
}

// Device represents a device in Terraform format.
type Device struct {
	Name       string
	Address    string
	Model      string
	Generation int
	App        string
}

const terraformTemplate = `# Shelly devices configuration
# Generated by shelly-cli

locals {
  {{.ResourceName}} = {
{{- range .Devices}}
    "{{.Name}}" = {
      address    = "{{.Address}}"
      model      = "{{.Model}}"
      generation = {{.Generation}}
{{- if .App}}
      app        = "{{.App}}"
{{- end}}
    }
{{- end}}
  }
}

# Example usage:
# resource "null_resource" "shelly_config" {
#   for_each = local.{{.ResourceName}}
#   triggers = {
#     address = each.value.address
#   }
# }
`

func run(ctx context.Context, opts *Options) error {
	ctx, cancel := context.WithTimeout(ctx, 2*shelly.DefaultTimeout)
	defer cancel()

	ios := opts.Factory.IOStreams()
	svc := opts.Factory.ShellyService()

	// Expand @all to all registered devices
	devices := cmdutil.ExpandDeviceArgs(opts.Devices)
	if len(devices) == 0 {
		return fmt.Errorf("no devices specified")
	}

	// Collect device data
	var tfDevices []Device

	err := cmdutil.RunWithSpinner(ctx, ios, "Fetching device data...", func(ctx context.Context) error {
		for _, device := range devices {
			var tfDev Device
			tfDev.Name = normalizeResourceName(device)

			// Get device config for address
			deviceCfg, exists := config.GetDevice(device)
			if exists {
				tfDev.Address = deviceCfg.Address
				tfDev.Model = deviceCfg.Model
				tfDev.Generation = deviceCfg.Generation
			}

			err := svc.WithConnection(ctx, device, func(conn *client.Client) error {
				info := conn.Info()
				tfDev.Model = info.Model
				tfDev.Generation = info.Generation
				tfDev.App = info.App
				return nil
			})

			if err != nil {
				// Use config data if device offline (already populated above)
				if !exists {
					continue
				}
			}

			tfDevices = append(tfDevices, tfDev)
		}
		return nil
	})
	if err != nil {
		return err
	}

	// Generate Terraform config
	tmpl, err := template.New("terraform").Parse(terraformTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	data := struct {
		ResourceName string
		Devices      []Device
	}{
		ResourceName: opts.ResourceName,
		Devices:      tfDevices,
	}

	// Output
	if opts.File == "" {
		return tmpl.Execute(ios.Out, data)
	}

	file, err := os.Create(opts.File)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer iostreams.CloseWithDebug("closing terraform export file", file)

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	ios.Success("Exported %d devices to %s", len(tfDevices), opts.File)
	return nil
}

// normalizeResourceName converts a device name to a valid Terraform identifier.
func normalizeResourceName(name string) string {
	result := strings.ToLower(name)
	result = strings.ReplaceAll(result, " ", "_")
	result = strings.ReplaceAll(result, "-", "_")
	result = strings.ReplaceAll(result, ".", "_")
	return result
}
