.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-input-trigger - Trigger input event


.SH SYNOPSIS
\fBshelly input trigger  [flags]\fP


.SH DESCRIPTION
Trigger an input event on a Shelly device.

.PP
Event types:
  single_push - Single button press
  double_push - Double button press
  long_push   - Long button press


.SH OPTIONS
\fB-e\fP, \fB--event\fP="single_push"
	Event type (single_push, double_push, long_push)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for trigger

.PP
\fB-i\fP, \fB--id\fP=0
	Input component ID (default 0)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Trigger single push event
  shelly input trigger living-room

  # Trigger double push event
  shelly input trigger living-room --event double_push

  # Trigger long push on specific input
  shelly input trigger living-room --id 1 --event long_push
.EE


.SH SEE ALSO
\fBshelly-input(1)\fP


.SH HISTORY
16-Dec-2025 Auto generated by spf13/cobra
