.nh
.TH "SHELLY" "1" "Feb 2026" "Shelly CLI" "User Commands"

.SH NAME
shelly-rgb-set - Set RGB parameters


.SH SYNOPSIS
\fBshelly rgb set  [flags]\fP


.SH DESCRIPTION
Set parameters of an RGB light component on the specified device.

.PP
You can set color values (red, green, blue) brightness, and on/off state.
Values not specified will be left unchanged.


.SH OPTIONS
\fB-b\fP, \fB--blue\fP=-1
	Blue value (0-255)

.PP
\fB--brightness\fP=-1
	Brightness (0-100)

.PP
\fB-g\fP, \fB--green\fP=-1
	Green value (0-255)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set

.PP
\fB-i\fP, \fB--id\fP=0
	RGB component ID (default 0)

.PP
\fB--on\fP[=false]
	Turn on

.PP
\fB-r\fP, \fB--red\fP=-1
	Red value (0-255)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB-F\fP, \fB--fields\fP[=false]
	Print available field names for use with --jq and --template

.PP
\fB-Q\fP, \fB--jq\fP=[]
	Apply jq expression to filter output (repeatable, joined with |)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB--offline\fP[=false]
	Only read from cache, error on cache miss

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--refresh\fP[=false]
	Bypass cache and fetch fresh data from device

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Set RGB color to red
  shelly rgb set living-room --red 255 --green 0 --blue 0

  # Set RGB with brightness
  shelly rgb color living-room -r 0 -g 255 -b 128 --brightness 75
.EE


.SH SEE ALSO
\fBshelly-rgb(1)\fP
