.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-script-get - Get script code or status


.SH SYNOPSIS
\fBshelly script get   [flags]\fP


.SH DESCRIPTION
Get the source code or status of a script on a Gen2+ device.

.PP
By default, displays the script source code. Use --status to show
detailed status including memory usage and errors.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get

.PP
\fB--status\fP[=false]
	Show script status instead of code


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Get script code
  shelly script get living-room 1

  # Get script status
  shelly script get living-room 1 --status
.EE


.SH SEE ALSO
\fBshelly-script(1)\fP
