.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-webhook-create - Create a webhook


.SH SYNOPSIS
\fBshelly webhook create  [flags]\fP


.SH DESCRIPTION
Create a new webhook for a device.

.PP
Webhooks are triggered by events and send HTTP requests to the specified URLs.
Common events include "switch.on", "switch.off", "input.toggle", etc.


.SH OPTIONS
\fB--cid\fP=0
	Component ID (default: 0)

.PP
\fB--disable\fP[=false]
	Create webhook in disabled state

.PP
\fB--event\fP=""
	Event type (e.g., switch.on, input.toggle)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--name\fP=""
	Webhook name (optional)

.PP
\fB--url\fP=[]
	Webhook URL (can be specified multiple times)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Create a webhook for switch on event
  shelly webhook create living-room --event "switch.on" --url "http://example.com/hook"

  # Create with multiple URLs
  shelly webhook create living-room --event "switch.off" --url "http://a.com" --url "http://b.com"

  # Create disabled webhook
  shelly webhook create living-room --event "input.toggle" --url "http://example.com" --disable
.EE


.SH SEE ALSO
\fBshelly-webhook(1)\fP
