.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-plugin-exec - Execute an extension


.SH SYNOPSIS
\fBshelly plugin exec  [args...] [flags]\fP


.SH DESCRIPTION
Execute an extension explicitly with the given arguments.

.PP
This is useful when the extension name conflicts with a built-in command
or when you want to explicitly invoke an extension.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for exec


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Run an extension
  shelly extension exec myext --some-flag

  # Run with arguments
  shelly extension exec myext arg1 arg2
.EE


.SH SEE ALSO
\fBshelly-plugin(1)\fP
