.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-completion-fish - Generate fish completion script


.SH SYNOPSIS
\fBshelly completion fish\fP


.SH DESCRIPTION
Generate the autocompletion script for fish.

.PP
To load completions in your current shell session:

.PP
shelly completion fish | source

.PP
To load completions for every new session, execute once:

.PP
shelly completion fish > ~/.config/fish/completions/shelly.fish


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for fish


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  shelly completion fish > ~/.config/fish/completions/shelly.fish
.EE


.SH SEE ALSO
\fBshelly-completion(1)\fP
