.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-action-set - Set an action URL for a Gen1 device


.SH SYNOPSIS
\fBshelly action set    [flags]\fP


.SH DESCRIPTION
Set an action URL for a Gen1 Shelly device.

.PP
Gen1 devices support various action types:
  - btn_on_url, btn_off_url: Button toggle actions
  - out_on_url, out_off_url: Output state change actions
  - roller_open_url, roller_close_url, roller_stop_url: Roller actions
  - longpush_url, shortpush_url: Button press duration actions

.PP
Note: This feature is currently in development.

.PP
Workaround: Use curl to set action URLs directly:
  curl "http:///settings?="


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Set output on action
  shelly action set living-room out_on_url "http://homeserver/api/light-on"

  # Workaround: use curl
  curl "http://192.168.1.100/settings?out_on_url=http%3A%2F%2Fhomeserver%2Fapi%2Flight-on"
.EE


.SH SEE ALSO
\fBshelly-action(1)\fP


.SH HISTORY
16-Dec-2025 Auto generated by spf13/cobra
