.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-webhook-update - Update a webhook


.SH SYNOPSIS
\fBshelly webhook update   [flags]\fP


.SH DESCRIPTION
Update an existing webhook.

.PP
Only specified fields will be updated. Use --enable or --disable to
change the webhook's active state.


.SH OPTIONS
\fB--disable\fP[=false]
	Disable webhook

.PP
\fB--enable\fP[=false]
	Enable webhook

.PP
\fB--event\fP=""
	Event type

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update

.PP
\fB--name\fP=""
	Webhook name

.PP
\fB--url\fP=[]
	Webhook URL (replaces all URLs)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Change webhook URL
  shelly webhook update living-room 1 --url "http://new-url.com"

  # Disable a webhook
  shelly webhook update living-room 1 --disable

  # Enable and change event
  shelly webhook update living-room 1 --enable --event "switch.off"
.EE


.SH SEE ALSO
\fBshelly-webhook(1)\fP
