.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-scene-show - Show scene details


.SH SYNOPSIS
\fBshelly scene show  [flags]\fP


.SH DESCRIPTION
Display detailed information about a scene including all its actions.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for show

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, yaml


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Show scene details
  shelly scene show movie-night

  # Output as JSON
  shelly scene show movie-night --output json

  # Using alias
  shelly scene info bedtime

  # Short form
  shelly sc show morning-routine
.EE


.SH SEE ALSO
\fBshelly-scene(1)\fP
