.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-thermostat-schedule-disable - Disable a schedule


.SH SYNOPSIS
\fBshelly thermostat schedule disable  [flags]\fP


.SH DESCRIPTION
Disable a schedule so it will not run until re-enabled.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for disable

.PP
\fB--id\fP=0
	Schedule ID to disable (required)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Disable schedule by ID
  shelly thermostat schedule disable gateway --id 1
.EE


.SH SEE ALSO
\fBshelly-thermostat-schedule(1)\fP
