.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-sensor-humidity - Manage humidity sensors


.SH SYNOPSIS
\fBshelly sensor humidity [flags]\fP


.SH DESCRIPTION
Manage humidity sensors on Shelly devices.

.PP
Humidity sensors (DHT22, HTU21D, or similar) provide relative humidity readings.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for humidity


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # List humidity sensors
  shelly sensor humidity list living-room

  # Get humidity reading
  shelly sensor humidity status living-room
.EE


.SH SEE ALSO
\fBshelly-sensor(1)\fP, \fBshelly-sensor-humidity-list(1)\fP, \fBshelly-sensor-humidity-status(1)\fP
