.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-plugin-list - List installed extensions


.SH SYNOPSIS
\fBshelly plugin list [flags]\fP


.SH DESCRIPTION
List installed extensions.

.PP
Extensions are external plugins that add new commands to the CLI. They
are standalone executables named 'shelly-*' that can be installed from
git repositories or created locally.

.PP
By default, only shows extensions installed in the user plugins directory.
Use --all to show all discovered extensions including those in PATH.

.PP
Output is formatted as a table by default. Use -o json or -o yaml for
structured output suitable for scripting.

.PP
Columns: Name, Version, Source (github/url/local/unknown), Path


.SH OPTIONS
\fB-a\fP, \fB--all\fP[=false]
	List all discovered extensions, not just installed ones

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose output


.SH EXAMPLE
.EX
  # List installed extensions
  shelly extension list

  # List all discovered extensions
  shelly extension list --all

  # Output as JSON
  shelly extension list -o json

  # Get extension names only
  shelly extension list -o json | jq -r '.[].name'

  # Find extensions without versions
  shelly extension list -o json | jq '.[] | select(.version == "")'

  # Short form
  shelly ext ls
.EE


.SH SEE ALSO
\fBshelly-plugin(1)\fP


.SH HISTORY
15-Dec-2025 Auto generated by spf13/cobra
