.nh
.TH "SHELLY" "1" "Jan 2026" "Shelly CLI" "User Commands"

.SH NAME
shelly-rgb-off - Turn rgb off


.SH SYNOPSIS
\fBshelly rgb off  [flags]\fP


.SH DESCRIPTION
Turn off a rgb component on the specified device.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for off

.PP
\fB-i\fP, \fB--id\fP=0
	RGB component ID (default 0)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--refresh\fP[=false]
	Bypass cache and fetch fresh data from device

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Turn off rgb
  shelly rgb off <device>

  # Turn off specific rgb ID
  shelly rgb off <device> --id 1
.EE


.SH SEE ALSO
\fBshelly-rgb(1)\fP
