.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-matter-enable - Enable Matter on a device


.SH SYNOPSIS
\fBshelly matter enable  [flags]\fP


.SH DESCRIPTION
Enable Matter connectivity on a Shelly device.

.PP
When Matter is enabled, the device can be commissioned (added) to
Matter-compatible smart home ecosystems like Apple Home, Google Home,
or Amazon Alexa.

.PP
After enabling, use 'shelly matter code' to get the pairing code
for commissioning the device.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for enable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Enable Matter
  shelly matter enable living-room

  # Then get pairing code
  shelly matter code living-room
.EE


.SH SEE ALSO
\fBshelly-matter(1)\fP
