.nh
.TH "SHELLY" "1" "Jan 2026" "Shelly CLI" "User Commands"

.SH NAME
shelly-plugin - Manage CLI plugins


.SH SYNOPSIS
\fBshelly plugin [flags]\fP


.SH DESCRIPTION
Manage CLI plugins (extensions).

.PP
Plugins are executable programs named shelly- that extend the CLI.
They can be installed from local files, GitHub repositories, or URLs.

.PP
Installed plugins are stored in ~/.config/shelly/plugins/.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for plugin


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--refresh\fP[=false]
	Bypass cache and fetch fresh data from device

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # List installed plugins
  shelly plugin list

  # Install from local file
  shelly plugin install ./shelly-myext

  # Install from GitHub
  shelly plugin install gh:user/shelly-myext

  # Remove a plugin
  shelly plugin remove myext

  # Run a plugin explicitly
  shelly plugin exec myext --some-flag

  # Create a new plugin scaffold
  shelly plugin create myext
.EE


.SH SEE ALSO
\fBshelly(1)\fP, \fBshelly-plugin-create(1)\fP, \fBshelly-plugin-exec(1)\fP, \fBshelly-plugin-install(1)\fP, \fBshelly-plugin-list(1)\fP, \fBshelly-plugin-remove(1)\fP, \fBshelly-plugin-upgrade(1)\fP
