.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-wifi-set - Configure WiFi connection


.SH SYNOPSIS
\fBshelly wifi set  [flags]\fP


.SH DESCRIPTION
Configure the WiFi station (client) connection for a device.

.PP
Set the SSID and password to connect to a WiFi network. Optionally configure
static IP settings instead of using DHCP.


.SH OPTIONS
\fB--disable\fP[=false]
	Disable WiFi station mode

.PP
\fB--dns\fP=""
	DNS server address (for static IP)

.PP
\fB--enable\fP[=false]
	Enable WiFi station mode

.PP
\fB--gateway\fP=""
	Gateway address (for static IP)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set

.PP
\fB--netmask\fP=""
	Network mask (for static IP)

.PP
\fB--password\fP=""
	WiFi password

.PP
\fB--ssid\fP=""
	WiFi network name

.PP
\fB--static-ip\fP=""
	Static IP address (uses DHCP if not set)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Connect to a WiFi network
  shelly wifi set living-room --ssid "MyNetwork" --password "secret"

  # Configure static IP
  shelly wifi set living-room --ssid "MyNetwork" --password "secret" \\
    --static-ip "192.168.1.50" --gateway "192.168.1.1" --netmask "255.255.255.0"

  # Disable WiFi station mode
  shelly wifi set living-room --disable
.EE


.SH SEE ALSO
\fBshelly-wifi(1)\fP


.SH HISTORY
16-Dec-2025 Auto generated by spf13/cobra
