.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-scene-import - Import a scene from file


.SH SYNOPSIS
\fBshelly scene import  [flags]\fP


.SH DESCRIPTION
Import a scene definition from a file.

.PP
Format is auto-detected from file extension (.json, .yaml, .yml).
Use --name to override the scene name from the file.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for import

.PP
\fB-n\fP, \fB--name\fP=""
	Override scene name from file

.PP
\fB--overwrite\fP[=false]
	Overwrite existing scene


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Import from YAML file
  shelly scene import scene.yaml

  # Import from JSON file
  shelly scene import scene.json

  # Import with different name
  shelly scene import scene.yaml --name my-scene

  # Overwrite existing scene
  shelly scene import scene.yaml --overwrite
.EE


.SH SEE ALSO
\fBshelly-scene(1)\fP
