.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-completion-zsh - Generate zsh completion script


.SH SYNOPSIS
\fBshelly completion zsh\fP


.SH DESCRIPTION
Generate the autocompletion script for zsh.

.PP
If shell completion is not already enabled in your environment you will need
to enable it. You can execute the following once:

.PP
echo "autoload -U compinit; compinit" >> ~/.zshrc

.PP
To load completions in your current shell session:

.PP
source <(shelly completion zsh)

.PP
To load completions for every new session, execute once:

.PP
shelly completion zsh > "${fpath[1]}/_shelly"


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for zsh


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  shelly completion zsh > ~/.zsh/completions/_shelly
.EE


.SH SEE ALSO
\fBshelly-completion(1)\fP
