.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-thermostat-set - Set thermostat configuration


.SH SYNOPSIS
\fBshelly thermostat set  [flags]\fP


.SH DESCRIPTION
Set thermostat configuration options.

.PP
Allows setting:
- Target temperature (--target)
- Operating mode (--mode): heat, cool, or auto
- Enable/disable state (--enable/--disable)


.SH OPTIONS
\fB--disable\fP[=false]
	Disable thermostat

.PP
\fB--enable\fP[=false]
	Enable thermostat

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for set

.PP
\fB--id\fP=0
	Thermostat component ID

.PP
\fB--mode\fP=""
	Operating mode (heat, cool, auto)

.PP
\fB--target\fP=0
	Target temperature in Celsius


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Set target temperature to 22°C
  shelly thermostat set gateway --target 22

  # Set mode to heat
  shelly thermostat set gateway --mode heat

  # Set target and mode together
  shelly thermostat set gateway --target 21 --mode auto

  # Enable thermostat
  shelly thermostat set gateway --enable
.EE


.SH SEE ALSO
\fBshelly-thermostat(1)\fP
