.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-script-update - Update a script


.SH SYNOPSIS
\fBshelly script update   [flags]\fP


.SH DESCRIPTION
Update an existing script on a Gen2+ Shelly device.

.PP
You can update the script name, code, or enabled status.
Use --append to add code to the existing script instead of replacing it.


.SH OPTIONS
\fB--append\fP[=false]
	Append code instead of replacing

.PP
\fB--code\fP=""
	Script code (inline)

.PP
\fB--enable\fP[=false]
	Enable the script

.PP
\fB-f\fP, \fB--file\fP=""
	Script code file

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update

.PP
\fB--name\fP=""
	Script name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose output


.SH EXAMPLE
.EX
  # Update script name
  shelly script update living-room 1 --name "New Name"

  # Update script code
  shelly script update living-room 1 --file script.js

  # Append code to existing script
  shelly script update living-room 1 --code "// More code" --append

  # Enable/disable script
  shelly script update living-room 1 --enable
.EE


.SH SEE ALSO
\fBshelly-script(1)\fP


.SH HISTORY
15-Dec-2025 Auto generated by spf13/cobra
