.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-device - Manage Shelly devices


.SH SYNOPSIS
\fBshelly device [flags]\fP


.SH DESCRIPTION
Manage Shelly devices in your registry.

.PP
Device commands allow you to add, remove, list, and manage registered devices.
Registered devices can be referenced by name in other commands.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for device


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # List all registered devices
  shelly device list

  # Get device info
  shelly dev info kitchen

  # Reboot a device
  shelly device reboot living-room
.EE


.SH SEE ALSO
\fBshelly(1)\fP, \fBshelly-device-factory-reset(1)\fP, \fBshelly-device-info(1)\fP, \fBshelly-device-list(1)\fP, \fBshelly-device-ping(1)\fP, \fBshelly-device-reboot(1)\fP, \fBshelly-device-status(1)\fP, \fBshelly-device-ui(1)\fP


.SH HISTORY
16-Dec-2025 Auto generated by spf13/cobra
