.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-schedule-update - Update a schedule


.SH SYNOPSIS
\fBshelly schedule update   [flags]\fP


.SH DESCRIPTION
Update an existing schedule on a Gen2+ Shelly device.

.PP
You can update the timespec, calls, or enabled status.


.SH OPTIONS
\fB--calls\fP=""
	JSON array of RPC calls to execute

.PP
\fB--disable\fP[=false]
	Disable the schedule

.PP
\fB--enable\fP[=false]
	Enable the schedule

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update

.PP
\fB--timespec\fP=""
	Cron-like time specification


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Update timespec
  shelly schedule update living-room 1 --timespec "0 0 9 * *"

  # Update calls
  shelly schedule update living-room 1 \\
    --calls '[{"method":"Switch.Set","params":{"id":0,"on":false}}]'

  # Enable/disable
  shelly schedule update living-room 1 --enable
  shelly schedule update living-room 1 --disable
.EE


.SH SEE ALSO
\fBshelly-schedule(1)\fP
