.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-light-toggle - Toggle light on/off


.SH SYNOPSIS
\fBshelly light toggle  [flags]\fP


.SH DESCRIPTION
Toggle a light component on or off on the specified device.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for toggle

.PP
\fB-i\fP, \fB--id\fP=0
	Light component ID (default 0)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Toggle light
  shelly light toggle <device>

  # Toggle specific light ID
  shelly light flip <device> --id 1
.EE


.SH SEE ALSO
\fBshelly-light(1)\fP
