.nh
.TH "SHELLY" "1" "Jan 2026" "Shelly CLI" "User Commands"

.SH NAME
shelly-export-terraform - Export devices as Terraform configuration


.SH SYNOPSIS
\fBshelly export terraform  [file] [flags]\fP


.SH DESCRIPTION
Export devices as Terraform local values configuration.

.PP
Creates a Terraform locals block with device information that can be
used as data source for infrastructure as code workflows.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for terraform

.PP
\fB--resource-name\fP="shelly_devices"
	Terraform local variable name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--refresh\fP[=false]
	Bypass cache and fetch fresh data from device

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Export to stdout
  shelly export terraform @all

  # Export to file
  shelly export terraform @all shelly.tf

  # Export with custom resource name
  shelly export terraform @all --resource-name my_shelly_devices
.EE


.SH SEE ALSO
\fBshelly-export(1)\fP
