.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-alias-list - List all command aliases


.SH SYNOPSIS
\fBshelly alias list [flags]\fP


.SH DESCRIPTION
Display all configured command aliases with their expansion.

.PP
Aliases are shortcuts that expand to longer commands. They can be either
command aliases (expand to shelly subcommands) or shell aliases (expand
to shell commands for more complex operations).

.PP
Output is formatted as a table by default. Use -o json or -o yaml for
structured output suitable for scripting.

.PP
Columns: Name, Command, Type (command/shell)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose output


.SH EXAMPLE
.EX
  # List all aliases
  shelly alias list

  # Output as JSON
  shelly alias list -o json

  # Get names of shell aliases
  shelly alias list -o json | jq -r '.[] | select(.shell) | .name'

  # Export aliases to backup file
  shelly alias list -o yaml > aliases-backup.yaml

  # Short form
  shelly alias ls
.EE


.SH SEE ALSO
\fBshelly-alias(1)\fP


.SH HISTORY
15-Dec-2025 Auto generated by spf13/cobra
