.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-sensoraddon-scan - Scan for OneWire devices


.SH SYNOPSIS
\fBshelly sensoraddon scan  [flags]\fP


.SH DESCRIPTION
Scan for OneWire devices on the Sensor Add-on bus.

.PP
Currently only DS18B20 OneWire temperature sensors are supported.

.PP
Note: This will fail if a DHT22 sensor is in use, as DHT22 shares
the same GPIOs as the OneWire bus.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for scan

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, yaml


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Scan for OneWire devices
  shelly sensoraddon scan kitchen

  # JSON output
  shelly sensoraddon scan kitchen -o json
.EE


.SH SEE ALSO
\fBshelly-sensoraddon(1)\fP
