.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-lora-config - Configure LoRa settings


.SH SYNOPSIS
\fBshelly lora config  [flags]\fP


.SH DESCRIPTION
Configure LoRa add-on settings on a Shelly device.

.PP
Allows setting radio parameters:
- Frequency: RF frequency in Hz (e.g., 868000000 for 868 MHz)
- Bandwidth: Channel bandwidth setting
- Data Rate: Spreading factor (higher = longer range, lower throughput)
- TX Power: Transmit power in dBm

.PP
Common frequencies:
- EU: 868 MHz (868000000)
- US: 915 MHz (915000000)
- Asia: 433 MHz (433000000)


.SH OPTIONS
\fB--bw\fP=0
	Bandwidth setting

.PP
\fB--dr\fP=0
	Data rate / spreading factor

.PP
\fB--freq\fP=0
	RF frequency in Hz

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for config

.PP
\fB--id\fP=100
	LoRa component ID

.PP
\fB--power\fP=0
	Transmit power in dBm


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Set frequency to 868 MHz (EU)
  shelly lora config living-room --freq 868000000

  # Set transmit power to 14 dBm
  shelly lora config living-room --power 14

  # Configure multiple settings
  shelly lora config living-room --freq 915000000 --power 20 --dr 7
.EE


.SH SEE ALSO
\fBshelly-lora(1)\fP


.SH HISTORY
16-Dec-2025 Auto generated by spf13/cobra
