.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-template-list - List configuration templates


.SH SYNOPSIS
\fBshelly template list [flags]\fP


.SH DESCRIPTION
List all saved configuration templates.

.PP
Templates are snapshots of device configuration that can be applied to
other devices of the same model. They're useful for provisioning multiple
devices with identical settings or backing up specific configurations.

.PP
Output is formatted as a table by default. Use -o json or -o yaml for
structured output suitable for scripting.

.PP
Columns: Name, Model, Gen, Source (device), Created


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose output


.SH EXAMPLE
.EX
  # List all templates
  shelly template list

  # Output as JSON
  shelly template list -o json

  # Find templates for a specific model
  shelly template list -o json | jq '.[] | select(.model | contains("Plus"))'

  # Get template names only
  shelly template list -o json | jq -r '.[].name'

  # Export templates list to backup file
  shelly template list -o yaml > templates-list.yaml

  # Short form
  shelly template ls
.EE


.SH SEE ALSO
\fBshelly-template(1)\fP


.SH HISTORY
15-Dec-2025 Auto generated by spf13/cobra
