.nh
.TH "SHELLY" "1" "Jan 2026" "Shelly CLI" "User Commands"

.SH NAME
shelly-virtual-get - Get a virtual component value


.SH SYNOPSIS
\fBshelly virtual get   [flags]\fP


.SH DESCRIPTION
Get the current value of a virtual component.

.PP
The key format is "type:id", for example "boolean:200" or "number:201".


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, yaml


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Get a boolean component
  shelly virtual get kitchen boolean:200

  # Get a number component with JSON output
  shelly virtual get kitchen number:201 -o json
.EE


.SH SEE ALSO
\fBshelly-virtual(1)\fP
