.nh
.TH "SHELLY" "1" "Feb 2026" "Shelly CLI" "User Commands"

.SH NAME
shelly-matter-disable - Disable Matter on a device


.SH SYNOPSIS
\fBshelly matter disable  [flags]\fP


.SH DESCRIPTION
Disable Matter connectivity on a Shelly device.

.PP
When Matter is disabled, the device will no longer be controllable
through Matter fabrics. Existing fabric pairings are preserved but
will not function until Matter is re-enabled.

.PP
To permanently remove all Matter pairings, use 'shelly matter reset'
instead.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for disable


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB--offline\fP[=false]
	Only read from cache, error on cache miss

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--refresh\fP[=false]
	Bypass cache and fetch fresh data from device

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Disable Matter
  shelly matter disable living-room

  # Re-enable later
  shelly matter enable living-room
.EE


.SH SEE ALSO
\fBshelly-matter(1)\fP
