.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-ping - Test device connectivity


.SH SYNOPSIS
\fBshelly ping  [flags]\fP


.SH DESCRIPTION
Test connectivity to a Shelly device.

.PP
Sends a request to the device's RPC API and measures response time.
This is useful for:
  - Checking if a device is online
  - Measuring network latency
  - Verifying device configuration

.PP
The device can be specified by registered name or IP address.


.SH OPTIONS
\fB-c\fP, \fB--count\fP=1
	Number of pings to send

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for ping

.PP
\fB--timeout\fP=5s
	Timeout for each ping


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Ping a device once
  shelly ping kitchen-light

  # Ping multiple times
  shelly ping kitchen-light -c 5

  # Ping with custom timeout
  shelly ping 192.168.1.100 --timeout 10s
.EE


.SH SEE ALSO
\fBshelly(1)\fP


.SH HISTORY
16-Dec-2025 Auto generated by spf13/cobra
