.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-bthome-add - Add a BTHome device


.SH SYNOPSIS
\fBshelly bthome add  [flags]\fP


.SH DESCRIPTION
Add a BTHome device to a Shelly gateway.

.PP
This command can either:
1. Start a discovery scan to find nearby BTHome devices
2. Add a specific device by MAC address

.PP
When scanning, the gateway will broadcast discovery requests and listen
for BTHome device advertisements. Discovered devices emit events that
can be monitored with 'shelly monitor events'.


.SH OPTIONS
\fB--addr\fP=""
	MAC address of device to add directly

.PP
\fB--duration\fP=30
	Discovery scan duration in seconds

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for add

.PP
\fB-n\fP, \fB--name\fP=""
	Name for the device (with --addr)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB--no-headers\fP[=false]
	Hide table headers in output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Start 30-second discovery scan
  shelly bthome add living-room

  # Custom scan duration (60 seconds)
  shelly bthome add living-room --duration 60

  # Add specific device by MAC address
  shelly bthome add living-room --addr 3c:2e:f5:71:d5:2a

  # Add device with a name
  shelly bthome add living-room --addr 3c:2e:f5:71:d5:2a --name "Door Sensor"
.EE


.SH SEE ALSO
\fBshelly-bthome(1)\fP
