.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-device-config-set - Set device configuration


.SH SYNOPSIS
\fBshelly device config set   =\&... [flags]\fP


.SH DESCRIPTION
Set configuration values for a device component.

.PP
Specify key=value pairs to update. Only the specified keys will be modified.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Set switch name
  shelly config set living-room switch:0 name="Main Light"

  # Set multiple values
  shelly config set living-room switch:0 name="Light" initial_state=on

  # Set light brightness default
  shelly config set living-room light:0 default.brightness=50
.EE


.SH SEE ALSO
\fBshelly-device-config(1)\fP
