.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-provision-ble - BLE-based provisioning (not yet implemented)


.SH SYNOPSIS
\fBshelly provision ble  [flags]\fP


.SH DESCRIPTION
Provision a device using Bluetooth Low Energy (BLE).

.PP
This command is intended for provisioning devices in AP mode that are not yet
connected to your network. BLE provisioning requires Bluetooth hardware support.

.PP
NOTE: This feature is not yet implemented. For now, connect to the device's AP
network and use 'shelly provision wifi' with the device's AP IP address (usually
192.168.33.1).


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for ble


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # BLE provisioning (future)
  shelly provision ble ShellyPlus1-ABCD1234

  # Current workaround: connect to device AP and use wifi provisioning
  # 1. Connect your computer to "ShellyPlus1-ABCD1234" WiFi network
  # 2. Run: shelly provision wifi 192.168.33.1
.EE


.SH SEE ALSO
\fBshelly-provision(1)\fP
