.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-party - Party mode \- flash lights!


.SH SYNOPSIS
\fBshelly party [device...] [flags]\fP


.SH DESCRIPTION
Start a party mode that rapidly toggles lights.

.PP
This is a fun command that makes your lights flash for a set duration.
For RGB lights, it cycles through random colors.

.PP
Use Ctrl+C to stop early.


.SH OPTIONS
\fB--all\fP[=false]
	Party with all registered devices

.PP
\fB-d\fP, \fB--duration\fP=30s
	Party duration

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for party

.PP
\fB-i\fP, \fB--interval\fP=500ms
	Toggle interval


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Party with all devices for 30 seconds
  shelly party --all

  # Party with specific devices for 1 minute
  shelly party light-1 light-2 -d 1m

  # Fast strobe effect (200ms interval)
  shelly party --all -i 200ms
.EE


.SH SEE ALSO
\fBshelly(1)\fP


.SH HISTORY
16-Dec-2025 Auto generated by spf13/cobra
