.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-plugin-upgrade - Upgrade extension(s)


.SH SYNOPSIS
\fBshelly plugin upgrade [name] [flags]\fP


.SH DESCRIPTION
Upgrade installed extension(s) to the latest version.

.PP
If a name is provided, upgrades only that extension.
Use --all to upgrade all installed extensions.

.PP
Note: This command checks GitHub for newer releases. Extensions must have been
originally installed from GitHub (the repo info is stored in plugin metadata).
For extensions installed from local files or URLs, you need to reinstall manually.


.SH OPTIONS
\fB-a\fP, \fB--all\fP[=false]
	Upgrade all installed extensions

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for upgrade


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--log-categories\fP=""
	Filter logs by category (comma-separated: network,api,device,config,auth,plugin)

.PP
\fB--log-json\fP[=false]
	Output logs in JSON format

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB--plain\fP[=false]
	Disable borders and colors (machine-readable output)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=0]
	Increase verbosity (-v=info, -vv=debug, -vvv=trace)


.SH EXAMPLE
.EX
  # Upgrade a specific extension (requires GitHub source)
  shelly extension upgrade myext

  # Check and upgrade all extensions
  shelly extension upgrade --all
.EE


.SH SEE ALSO
\fBshelly-plugin(1)\fP
