.nh
.TH "SHELLY" "1" "Dec 2025" "Shelly CLI" "User Commands"

.SH NAME
shelly-thermostat-boost - Activate boost mode


.SH SYNOPSIS
\fBshelly thermostat boost  [flags]\fP


.SH DESCRIPTION
Activate boost mode on a thermostat.

.PP
Boost mode sets the valve to 100% for rapid heating. This is useful
when you need to quickly warm up a room.

.PP
Use --duration to specify how long boost mode should last.
Use --cancel to cancel an active boost.


.SH OPTIONS
\fB--cancel\fP[=false]
	Cancel active boost

.PP
\fB-d\fP, \fB--duration\fP=0s
	Boost duration (e.g., 5m, 30m, 1h)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for boost

.PP
\fB--id\fP=0
	Thermostat component ID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Config file (default $HOME/.config/shelly/config.yaml)

.PP
\fB--no-color\fP[=false]
	Disable colored output

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format (table, json, yaml, template)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--template\fP=""
	Go template string for output (use with -o template)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Enable verbose output


.SH EXAMPLE
.EX
  # Activate boost with device default duration
  shelly thermostat boost gateway

  # Boost for 5 minutes
  shelly thermostat boost gateway --duration 5m

  # Boost for 30 minutes
  shelly thermostat boost gateway --duration 30m

  # Cancel active boost
  shelly thermostat boost gateway --cancel
.EE


.SH SEE ALSO
\fBshelly-thermostat(1)\fP


.SH HISTORY
15-Dec-2025 Auto generated by spf13/cobra
