package export

import (
	"bytes"
	"strings"
	"text/template"

	"github.com/tj-smith47/shelly-cli/internal/shelly"
)

// TerraformDevice represents a device in Terraform format.
type TerraformDevice struct {
	Name       string
	Address    string
	Model      string
	Generation int
	App        string
}

// TerraformTemplate is the template for generating Terraform configuration.
const TerraformTemplate = `# Shelly devices configuration
# Generated by shelly-cli

locals {
  {{.ResourceName}} = {
{{- range .Devices}}
    "{{.Name}}" = {
      address    = "{{.Address}}"
      model      = "{{.Model}}"
      generation = {{.Generation}}
{{- if .App}}
      app        = "{{.App}}"
{{- end}}
    }
{{- end}}
  }
}

# Example usage:
# resource "null_resource" "shelly_config" {
#   for_each = local.{{.ResourceName}}
#   triggers = {
#     address = each.value.address
#   }
# }
`

// TerraformData holds the data for terraform template rendering.
type TerraformData struct {
	ResourceName string
	Devices      []TerraformDevice
}

// BuildTerraformConfig builds Terraform configuration from device data.
// The resourceName parameter sets the local variable name (default: "shelly_devices").
func BuildTerraformConfig(devices []shelly.DeviceData, resourceName string) (string, error) {
	// Convert to terraform Device format with normalized names
	tfDevices := make([]TerraformDevice, 0, len(devices))
	for _, d := range devices {
		tfDevices = append(tfDevices, TerraformDevice{
			Name:       NormalizeResourceName(d.Name),
			Address:    d.Address,
			Model:      d.Model,
			Generation: d.Generation,
			App:        d.App,
		})
	}

	// Generate Terraform config
	tmpl, err := template.New("terraform").Parse(TerraformTemplate)
	if err != nil {
		return "", err
	}

	data := TerraformData{
		ResourceName: resourceName,
		Devices:      tfDevices,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// NormalizeResourceName converts a device name to a valid Terraform identifier.
func NormalizeResourceName(name string) string {
	result := strings.ToLower(name)
	result = strings.ReplaceAll(result, " ", "_")
	result = strings.ReplaceAll(result, "-", "_")
	result = strings.ReplaceAll(result, ".", "_")
	return result
}
