name: AutoTag

# Auto-tags on push to master based on commit message:
#   #major - bump major version (1.0.0 -> 2.0.0)
#   #minor - bump minor version (1.0.0 -> 1.1.0)
#   #patch - bump patch version (default) (1.0.0 -> 1.0.1)
#   #none  - skip tagging (use when pushing workflow changes)
#
# For RC releases, create and push tag manually:
#   git tag -a v1.0.0-rc.1 -m "Release Candidate 1"
#   git push origin v1.0.0-rc.1

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#none') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_BRANCHES: master
          TAG_CONTEXT: branch
          WITH_V: true
